#!/bin/bash

if ! git --version > /dev/null; then
	echo "Need git installed"
	exit 1
fi

if ! rake --version > /dev/null; then
	echo "Need rake installed"
	exit 1
fi

mkdir -pv $HOME/share/bin

if [ ! -d $HOME/.oh-my-zsh ]; then
	echo "Installing oh-my-zsh"
	git clone https://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
fi

if [ ! -d $HOME/share/bin/hub ]; then
	echo "Installing hub"
	git clone git://github.com/github/hub.git $HOME/.hub
	( cd ~/.hub && PREFIX=$HOME/share rake install )
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for FILE in `ls $DIR | grep -Ev "install|vim.dotfiles"`; do
	if [ ! -L $HOME/.$FILE ]; then
		if [ ! -d $HOME/.$FILE ]; then
			echo "Installing .$FILE"
			ln -sv $DIR/$FILE $HOME/.$FILE
		fi
	fi
done

for SUBDIR in `ls $DIR/vim.dotfiles | grep -v bundle`; do
	mkdir -pv $HOME/.vim/$SUBDIR
	for FILE in `ls $DIR/vim.dotfiles/$SUBDIR`; do
		if [ ! -L $HOME/.vim/$SUBDIR/$FILE ]; then
			echo "Installing .vim/$SUBDIR/$FILE"
			ln -sv $DIR/vim.dotfiles/$SUBDIR/$FILE $HOME/.vim/$SUBDIR/$FILE
		fi
	done
done
for FILE in `ls $DIR/vim.dotfiles/bundle | grep -v README`; do
	if [ ! -d $HOME/.vim/bundle/$FILE ]; then
		echo "Installing `cat $DIR/vim.dotfiles/bundle/$FILE` into vim"
		git clone `cat $DIR/vim.dotfiles/bundle/$FILE` $HOME/.vim/bundle/$FILE
	fi
done
