#!/bin/bash

if ! git --version > /dev/null; then
	echo "Need git installed"
	exit 1
fi

if ! rake --version > /dev/null; then
	echo "Need rake installed"
	exit 1
fi

mkdir -pv $HOME/share/bin
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for FILE in `ls $DIR | grep -Ev "install|vim"`; do
	if [ ! -L $HOME/.$FILE ]; then
		if [ ! -d $HOME/.$FILE ]; then
			echo "Installing .$FILE"
			ln -sv $DIR/$FILE $HOME/.$FILE
		fi
	fi
done

for SUBDIR in `ls $DIR/vim | grep -v bundle`; do
	mkdir -pv $HOME/.vim/$SUBDIR
	for FILE in `ls $DIR/vim/$SUBDIR`; do
		if [ ! -L $HOME/.vim/$SUBDIR/$FILE ]; then
			echo "Installing .vim/$SUBDIR/$FILE"
			ln -sv $DIR/vim/$SUBDIR/$FILE $HOME/.vim/$SUBDIR/$FILE
		fi
	done
done
for FILE in `ls $DIR/vim/bundle | grep -v README`; do
	if [ ! -d $HOME/.vim/bundle/$FILE ]; then
		echo "Installing `cat $DIR/vim/bundle/$FILE` into vim"
		git clone `cat $DIR/vim/bundle/$FILE` $HOME/.vim/bundle/$FILE
	fi
done

if [ ! -f $HOME/share/bin/hub ]; then
	echo "Installing hub"
	( cd ~/.hub && PREFIX=$HOME/share rake install )
fi

